version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

jobs:
  test-site:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn && pip3 install -r requirements.txt && pip3 install gunicorn
      - run:
          name: Build the site resources
          command: yarn run build
      - run:
          name: Run the site server
          command: WEBSERVICE_URL=https://example.com AUTH_TOKEN=fake gunicorn assets_manager.wsgi -b 0.0.0.0:80
          background: true
      - run:
          name: Check site is accessible
          command: sleep 3 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://localhost
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 black
      - run:
          name: Lint python code
          command: yarn lint-python
  test-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run python tests
          command: WEBSERVICE_URL=https://example.com AUTH_TOKEN=fake ./manage.py test
workflows:
  version: 2
  build:
    jobs:
      - test-site
      - lint-scss
      - lint-python
      - test-python
