version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

jobs:
  lint-scss:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint sass
          command: yarn lint-scss
  lint-python:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 black
      - run:
          name: Lint python code
          command: yarn lint-python
workflows:
  version: 2
  build:
    jobs:
      - lint-scss
      - lint-python
